spring.application.name=EasyNote
server.port=8082

base1.datasource.jdbcUrl=jdbc:mysql://${DB1_HOST}:${DB1_PORT}/${DB1_NAME}
base1.datasource.username=${DB1_USER}
base1.datasource.password=${DB1_PASS}
base1.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

