spring.application.name=EasyNote
server.port=8081

base1.datasource.jdbcUrl=jdbc:mysql://localhost:3307/EasyNote2
base1.datasource.username=root
base1.datasource.password=Be@2003Schin
base1.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

